server:
  port: 8091

eureka:
  instance:
    instance-id: ${spring.application.name}.${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://192.168.99.100:8761/eureka
     # defaultZone: http://localhost:8761/eureka
      
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:dbservice
    username: secure
    password: secure
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect 
  application:    name: account-login-service
  rabbitmq:
   host: 192.168.99.100
   port: 5672
  
  cloud:
   bus:
      enabled: true
      destination: configXchangebus
   stream:
      bindings:
       loginChannel:
           destination: orders
    
    
