--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: auditms
    version: v1
  name: auditms
  namespace: logs
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: auditms
      version: v1
  template: 
    metadata: 
      labels: 
        app: auditms
        version: v1

    spec: 

      containers: 
        - 
          image: "prashantadockertest/auditms:1"
          imagePullPolicy: Always
          name: auditms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8096
            hostPort: 8096      
          env:
            - name: auditms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    