--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: loginms
    version: v1
  name: loginms
  namespace: logs
spec: 
  ports: 
    - 
      name: http
      port: 8091
      targetPort: 8091
  selector: 
    app: loginms
    version: v1
  type: NodePort