--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: loginms
    version: v1
  name: loginms
  namespace: logs
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: loginms
      version: v1
  template: 
    metadata: 
      labels: 
        app: loginms
        version: v1

    spec: 

      containers: 
        - 
          image: "prashantadockertest/loginms:1"
          imagePullPolicy: Always
          name: loginms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8091
            hostPort: 8091      
          env:
            - name: loginms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    