server:  
  port: ${PORT:8765}

spring:  
  application:
    name: gateway-server
       
zuul:
  routes:  
    oauth:
      path: /oauth/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: login
    product:
      path: /product/**
      sensitiveHeaders: 
      serviceId: product-service
    order:
      path: /order/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: orders-service
            
eureka:
  instance:
    instance-id: ${spring.application.name}.${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    
security:
   oauth2:
    resource:
     token-info-uri: http://localhost:8082/oauth/check_token
    client:
     client-id: web
     client-secret: webpass
     access-token-uri: http://localhost:8082/oauth/token
     user-authorization-uri: http://localhost:8082/oauth/authorize   
   

#security:
  
  #user:
  #  name: Prashanta
  #  password: Prashanta123
  
  #oauth2:
 #   resource:
  #   token-info-uri: http://localhost:8082/oauth/check_token
  #  client:
  #    client-id: web
  #    client-secret: webpass

#security:
# oauth2:
#   client:
#     accessTokenUri: http://localhost:8765/uua/oauth/token
#     userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#    client-id: web
#     client-secret: webpass
#      clientAuthenticationScheme: form
#    resource:
#      userInfoUri: http://localhost:8765/uaa/user
#      preferTokenInfo: false  
# sessions: ALWAYS 

#proxy:
#  auth:
#    routes:
#      customer: oauth2
#      account: oauth2
          
#security:
#  oauth2:
#    sso:
#      loginPath: /uaa/login      
#    client:
#      accessTokenUri: http://localhost:8765/uua/oauth/token
#      userAuthorizationUri: http://localhost:8765/uua/oauth/authorize
#      clientId: acme
#      clientSecret: secret
#      clientAuthenticationScheme: form   
#    resource:
#      userInfoUri: http://localhost:9999/user
#      preferTokenInfo: false  
#  sessions: ALWAYS 