--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: orderms
    version: v1
  name: orderms
  namespace: logs
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: orderms
      version: v1
  template: 
    metadata: 
      labels: 
        app: orderms
        version: v1

    spec: 

      containers: 
        - 
          image: "prashantadockertest/orderms:1"
          imagePullPolicy: Always
          name: orderms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8097
            hostPort: 8097      
          env:
            - name: orderms.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    