--- 
apiVersion: v1
kind: Service
metadata: 
  labels: 
    app: orderms
    version: v1
  name: orderms
  namespace: logs
spec: 
  ports: 
    - 
      name: http
      port: 8097
      targetPort: 8097
  selector: 
    app: orderms
    version: v1
  type: NodePort