DROP TABLE IF EXISTS CONVERSION_DETAILS;

CREATE TABLE CONVERSION_DETAILS ( id INT AUTO_INCREMENT PRIMARY KEY, country_code CHAR(3) NOT NULL, conversion_factor decimal(30,3) NOT NULL, CONSTRAINT UC_CONVERSION_DETAILS UNIQUE (country_code));  
INSERT INTO CONVERSION_DETAILS (country_code,conversion_factor) VALUES
('US',75.62), 
('EU',85.32),  
('AU',52.73),
('FR',85.37);  
