--- 
apiVersion: apps/v1
kind: Deployment
metadata: 
  labels: 
    app: productms
    version: v1
  name: productms
  namespace: logs
spec: 
  strategy: # Default, so usually not specified
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1  # specifies the maximum number of Pods that can be created over the desired number of Pods
      maxUnavailable: 25% #specifies the maximum number of Pods that can be unavailable during the update process
  replicas: 1
  selector: 
    matchLabels: 
      app: productms
      version: v1
  template: 
    metadata: 
      labels: 
        app: productms
        version: v1

    spec: 

      containers: 
        - 
          image: "prashantadockertest/productservice:1"
          imagePullPolicy: Always
          name: productms
          ports: 
#          - containerPort: 8081   
          - name: httpport
            containerPort: 8093
            hostPort: 8093      
          env:
            - name: conversionfactor.eureka.url
              value: "http://eureka:8761/eureka"  

              
                    