server:
  port: 8092

spring:
  h2:
    console:
      enabled: true
  datasource:
     url: jdbc:h2:mem:dbservice
     username: secure
     password: secure
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  application:
    name: orders-service
      
 #Eureka server mapping
eureka:
  instance:
    instance-id: ${spring.application.name}.${random.int}
    lease-expiration-duration-in-seconds: 2
    lease-renewal-interval-in-seconds: 1
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka 
#security:
#   oauth2:
#    resource:
#     token-info-uri: http://localhost:8082/oauth/check_token
#    client:
#     client-id: web
#     client-secret: webpass
#    access-token-uri: http://localhost:8082/oauth/token
#     user-authorization-uri: http://localhost:8082/oauth/authorize   
 
 